MACHINEOVERRIDES =. "raspberrypi3-64:"

require conf/machine/raspberrypi3-64.conf
require conf/machine/include/panel-waveshare35b.inc

ENABLE_UART = "1"
ENABLE_SPI_BUS = "1"
RPI_EXTRA_CONFIG = "dtoverlay=${PANEL_DTOVERLAY}\ndtoverlay=disable-bt"
DISPLAY_ROTATE = "0"
DISABLE_VC4GRAPHICS = "1"
DISABLE_RPI_BOOT_LOGO = "1"
RPI_USE_U_BOOT = "1"
SERIAL_CONSOLES = "115200;ttyAMA0"

IMAGE_BOOT_FILES:append = " ${PANEL_DTOVERLAY}.dtbo;overlays/${PANEL_DTOVERLAY}.dtbo"