require conf/distro/poky.conf


DISTRO = "my-distro"
DISTRO_NAME = "My Distro"
DISTRO_VERSION = "0.1"

DISTRO_FEATURES:append = " usrmerge systemd"
DISTRO_FEATURES:remove = "x11 wayland"
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = ""
VIRTUAL-RUNTIME_login_manager = "shadow-base"


DISTRO_FEATURES_BACKFILL_CONSIDERED += "sysvinit"
PACKAGECONFIG:append:pn-qtbase = " linuxfb"
ENABLE_UART = "1"
RPI_EXTRA_CONFIG = "\n\
dtoverlay=piscreen,drm\n\
"
